### ISSUE TITLE
Timezone on Campaign

### ISSUE THREAD

**Issue by benwilkerson** [morelup/Five9-Call-Flow-Addin-Issues#25]

**Comment by benwilkerson** [comment]
Create a box to enter timezone on the Campaign for documentation.

**Comment by morelup** [comment]
Added as a freeform text field, as well as on the project information page.  Hopefully at some point i'll be able to get the campaign shape to default to that value but ATM more trouble that it is worth.

If someone wants to throw together a full list I can make it a dropdown instead of a free form text.
