### ISSUE TITLE
Menu module - font for the Prompt name doesn't change 

### ISSUE THREAD

**Issue by HeatherRix** [morelup/Five9-Call-Flow-Addin-Issues#45]
Selected the shape, changed font down a size, prompt name remained the same size but other elements in the shape changed font size.

**Comment by morelup** [comment]
Not intended to allow font changes on the shapes, but i removed the lock on the format for that part of the shape to let you do this.  Most of the shapes would need to have a good bit of reformatting to allow the shape to compress with the font (also the DTMF won't shrink due to the interconnection of shape sizes)
